### ISSUE TITLE
How do I use ~text with this library?

### ISSUE THREAD

**Issue by adamtester** [imgix/imgix-php#13]
Is it possible to add multiline text using this?

**Comment by paulstraw** [comment]
Hey @adamtester, that shouldn't be a problem at all. Since the text endpoint just lives at the `/~text` URL of your source, you should just be able to do the following:

``` php
$params = array("txt64" => "hello, world! 👌");
$textURL = $builder->createURL("~text", $params);
```

At that point, you can just use `$textURL` anywhere else, such as the `mark64` param of another imgix URL.

Hopefully that answers your question. I'm going to close this issue, but please feel free to reopen it if you're still having any trouble with this!
