### ISSUE TITLE
Describe an easy example for purge images in PHP

### ISSUE THREAD

**Issue by shakaran** [imgix/imgix-php#25]
According to the documentation [about purging images](https://docs.imgix.com/setup/purging-images) it shows an example for purge via Python, but it seems that there is no example in PHP or a method in this SDK library that implements this in a easy way

It is clear that must obey 3 conditions:

1) Request to https://api.imgix.com/v2/image/purger
2) Use the api key param
3) Know the url to purge

In Curl is using like:

```
curl "https://api.imgix.com/v2/image/purger" \
  -u "$API_KEY:" \
  -d "url=$URL_TO_PURGE"

```

**Comment by haktansuren** [comment]
Simply replace `{IMAGE_URL}` and `{API_KEY}` accordingly @shakaran...


```php
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.imgix.com/v2/image/purger");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"url\":\"{IMAGE_URL}\"}");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_USERPWD, {API_KEY});

$headers = array();
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
```

**Comment by atrauzzi** [comment]
Hmm, I think the desire is to have a method in the SDK that can abstract all this request building away.

**Comment by jayeb** [comment]
Hey folks,

Sorry for the radio silence in this thread. Adding "native" purging into our core SDK libraries is something we're planning to do in the near-to-medium future. We resisted this for a long time because we didn't think that it was worth "cluttering" the core libraries with something that was easily accomplishable in any language with a native HTTP request, but we've since come around and now agree with @atrauzzi: abstracting the messy, curly bits away from common imgix actions such as purging is exactly what this library should be doing.

If anyone wants to take a swing at this we'd happily accept a PR, but otherwise stay tuned 😄.

**Comment by zipus** [comment]
Sorry, you mark this as completed, I don't see any commit or any docs about a sdk method, only the http default request.

**Comment by jayeb** [comment]
@zipus I'm no longer working on this project, but I'll tag in @sherwinski here!

**Comment by sherwinski** [comment]
Hey @zipus,
Nowadays we have a [separate API](https://docs.imgix.com/apis/management) for operations like purging, which we are planning to build out support for through a new set of SDKs. For right now we only have a [JavaScript library](https://github.com/imgix/imgix-management-js) for it, but if you're interested in a php-specific client let me know and I'll add a +1 to our item in the backlog for it.
