### ISSUE TITLE
Tag a new release with latest changes in master

### ISSUE THREAD

**Issue by shakaran** [imgix/imgix-php#84]
Current [release 3.3.1](https://github.com/imgix/imgix-php/tree/3.3.1) is from march 2021.

It would be nice if the new changes  in master are added maybe in a minor 3.3.2 or maybe 3.4.

**Comment by luqven** [comment]
Hey @shakaran, thanks for pointing this out.

We typically only cut releases for this library for feature changes or fixes. The commits since march don't appear to fall under that criteria.

We're looking into transitioning to some sort of semantic release so that this process will be more automated moving forward, but I can't give you a timetable at this time.

For now, I'm going to close this issue, but please re-open it if there is a pressing need for a new release.
